### PR TITLE
Allow to provide filename by command line or env var.

### PR DESCRIPTION
**Pull request by AlKoFDC**
I noticed that the environment variable is gotten, but actually never used.
After changing the package name I also ran in some errors, that will still occur with the small change I did, but at least it generates the file correctly.

### CODE REVIEW

**Comment by AlKoFDC** [comment]
Maybe it would just be better to make the package name not adjustable at all.

**Comment by vincent-petithory** [comment]
Although not used in the parser, the GOFILE env var is checked to ensure we come from `go generate` (as well as GOPKG, and yes as you pointed out, the package name isn't meant to be changed).

However GOFILE should not be used to pass the txt file to parse as your 2nd commit does. It's set by go generate to designate from which go file the go generate line comes from.

**Comment by vincent-petithory** [comment]
I took the liberty to cherry-pick your first commit which uses the goPkg var where possible, which makes sense, and I updated the generated countries file. Thanks again!

**Comment by AlKoFDC** [comment]
I see. I didn't work with go generate before, so didn't know of this. That means my fork is kind of broken. (:

**Pull request closed without merging**
